version: "3.4"
services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:6
    command: -url=jdbc:postgresql://postgres:5432/todo -user=postgres -password=postgres -connectRetries=10 migrate
    volumes:
      - ./db/sql:/flyway/sql
    depends_on:
      - postgres
